### ISSUE TITLE
the evaluation can not successfully run with the example testdata

### ISSUE THREAD

**Issue by sherlock666** [woven-visionai/wts-dataset#5]
without any code change i got:

Error: ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File "g:/aicity-track2/evaluation/eval-metrics-AIC-Track2/metrics.py", line 222, in <module>
    metrics_pedestrian_mean = compute_mean_metrics(metrics_pedestrian_overall, num_segments_overall)
  File "g:/aicity-track2/evaluation/eval-metrics-AIC-Track2/metrics.py", line 174, in compute_mean_metrics
    metrics_mean[metric_name] /= num_segments_overall
ZeroDivisionError: division by zero

**Comment by woven-visionai** [comment]
did you use our example data and example gt file for this test, we test again and can not reproduce this error.

**Comment by sherlock666** [comment]
yes i use the json inside the testdata
i even print out the pred_all gt_all to make sure that the path is correct (without changing other thing)

**Comment by woven-visionai** [comment]
Could you please check you are using the nltk>=3.8? 

We also updated our evaluation code for the challenge purpose. Could you please have a try?

**Comment by woven-visionai** [comment]
Hi, thanks for sharing this issue. In order to reproduce your issue on my side, could you please share below?
- Your local directory structure
- Your command
- From which directory you ran the command

From my side, in order to test with the toy test data, I use the latest evaluation code repo and run 
`python metrics_test.py --pred testdata/pred_identical.json`
from folder `evaluation/eval-metrics-AIC-Track2`. I currently don't see any error from this command.
